# Choose a base image
FROM ubuntu:latest

# Install Requirements
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

# Create a new folder for our application
RUN mkdir /app

# Set the working directory when our container executes
WORKDIR /app

# Copy the rest of our application 
COPY . /app

# Install app dependencies
RUN pip install -r requirements.txt


#Expose our application port
EXPOSE 5000

# Set start command
CMD [ "python", "app.py" ]
